### ISSUE TITLE
Admission control webhook check should check apiGroups

### ISSUE THREAD

**Issue by adamwg** [digitalocean/clusterlint#93]
The admission control webhook check in the `doks` group will currently throw an error for webhooks that apply only to CRDs, but such webhooks would never actually cause a problem for DOKS upgrades since they won't prevent pods from starting. The admission control webhook check should ignore any webhook configuration that doesn't apply to resources in the `v1` or `apps/v1` apiGroups.

**Comment by zbigniev** [comment]
Hi @adamwg, want to try giving this a shot. If you could give me some pointers on where to start, that'll be great.

**Comment by adamwg** [comment]
@zbigniev The `admission-controller-webhook-replacement` check iterates over webhook configurations and [ignores them if they meet various conditions](https://github.com/digitalocean/clusterlint/blob/master/checks/doks/admission_controller_webhook_replacement.go#L56) - e.g., if their `FailurePolicy` is `Ignore`. We should add a check for which API groups the configuration applies to. These are configured in the `Rules` field of the configuration. The [k8s reference docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io) and [k8s Go client docs](https://godoc.org/k8s.io/api/admissionregistration/v1beta1) for webhooks will probably be helpful here.

**Comment by zbigniev** [comment]
@adamwg thanks for the details. I looked at the code and have some sense of whats to be done. I guess, the need for this issue came from [this](https://kubernetes.slack.com/archives/CCPETNUCA/p1598549516051000) conversation. 
However, I am unable to completely understand the statement -  _admission control webhook check should ignore any webhook configuration that doesn't apply to resources in the v1 or apps/v1 apiGroups_. Does it imply that another check be added, which checks whether `apiGroups` stated in the configuration are (all?) present in apiGroups `v1` or `apps/v1` (yet to figure out how to get that exhaustive list)?
It'll be great if you could help; here or on Slack. Thanks a lot.

**Comment by adamwg** [comment]
@zbigniev Sorry for the delay getting back to you on this!

The idea here is to check the `apiGroups` and `apiVersions` in each of the `rules` of the webhook config, and generate diagnostics only if the `v1` or `apps/v1` groups are included. Feel free to reach out on Slack if you need any more guidance!
